
- path: output/reject.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_reject_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/reject.txt"
      format: txt
      behavior: classical

    skk_reject_domainset:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/reject.txt"
      format: txt
      behavior: domain

    skk_reject_reject_non_ip_no_drop:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/reject-no-drop.txt"
      format: txt
      behavior: classical


- path: output/reject_drop.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_reject_non_ip_drop:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/reject-drop.txt"
      format: txt
      behavior: classical


- path: output/reject@ip.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_reject_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/reject.txt"
      format: txt
      behavior: classical


- path: output/direct.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_domestic:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/domestic.txt"
      format: txt
      behavior: classical

    skk_direct_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/direct.txt"
      format: txt
      behavior: classical

    xkww3n_domestic:
      type: http
      url: "https://rules.xkww3n.cyou/text-plus/domestic.txt"
      format: txt
      behavior: domain

    my_direct:
      type: file
      path: local/direct.yaml
      format: yaml
      behavior: classical


- path: output/direct@ip.yaml
  format: yaml
  behavior: classical
  upstream:
 
    pmkol_china_ip:
      type: http
      url: "https://raw.githubusercontent.com/pmkol/easymosdns/rules/china_ip_list.txt"
      format: txt
      behavior: ipcidr

    metowolf_china_ip:
      type: http
      url: "https://metowolf.github.io/iplist/data/special/china.txt"
      format: txt
      behavior: ipcidr


- path: output/microsoft@cn.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_microsoft_cdn:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt"
      format: txt
      behavior: classical

    dustinwin_microsoft_cn:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.yaml"
      format: yaml
      behavior: domain


- path: output/apple@cn.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_apple_services:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/apple_services.txt"
      format: txt
      behavior: classical

    skk_apple_cn:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt"
      format: txt
      behavior: classical

    skk_apple_cdn:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt"
      format: txt
      behavior: domain

    dustinwin_apple_cn:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.yaml"
      format: yaml
      behavior: domain


- path: output/games@cn.yaml
  format: yaml
  behavior: classical
  upstream:
    
    dustinwin_game_cn:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.yaml"
      format: yaml
      behavior: domain


- path: output/ai.yaml
  format: yaml
  behavior: classical
  upstream:
    
    dustinwin_ai:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.yaml"
      format: yaml
      behavior: domain

    repcz_ai:
      type: http
      url: "https://github.com/Repcz/Tool/raw/X/mihomo/Rules/AI.list"
      format: txt
      behavior: classical

- path: output/cdn.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_cdn_domainset:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/cdn.txt"
      format: txt
      behavior: domain

    skk_cdn:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/cdn.txt"
      format: txt
      behavior: classical

    skk_download_domainset:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/download.txt"
      format: txt
      behavior: domain

    skk_download:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/download.txt"
      format: txt
      behavior: classical

    skk_download_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/download.txt"
      format: txt
      behavior: classical

- path: output/telegram.yaml
  format: yaml
  behavior: classical
  upstream:
    
    telegram_non_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/telegram.txt"
      format: txt
      behavior: classical

    telegram_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/telegram.txt"
      format: txt
      behavior: classical


- path: output/lan.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_lan:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/lan.txt"
      format: txt
      behavior: classical

    dustinwin_private:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.yaml"
      format: yaml
      behavior: domain


- path: output/lan@ip.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_lan_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/lan.txt"
      format: txt
      behavior: classical

    dustinwin_privateip:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.yaml"
      format: yaml
      behavior: ipcidr


- path: output/fakeip-filter.yaml
  format: yaml
  behavior: classical
  upstream:
    
    skk_fake_ip_filter:
      type: http
      url: "https://ruleset.skk.moe/Clash/domainset/clash_fake_ip_filter.txt"
      format: txt
      behavior: domain

    dustinwin_fake_ip_filter:
      type: http
      url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.yaml"
      format: yaml
      behavior: domain


- path: output/media.yaml
  format: yaml
  behavior: classical
  upstream:

    Repcz_Emby:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Repcz/Tool@X/mihomo/Rules/Emby.list"
      format: txt
      behavior: classical

    skk_stream:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/stream.txt"
      format: txt
      behavior: classical

    skk_stream_ip:
      type: http
      url: "https://ruleset.skk.moe/Clash/ip/stream.txt"
      format: txt
      behavior: classical


- path: output/proxy.yaml
  format: yaml
  behavior: classical
  upstream:

    GFWatch:
      type: http
      url: "https://rules.xkww3n.cyou/text-plus/proxy.txt"
      format: txt
      behavior: domain

    gfwlist:
      type: http
      url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
      format: yaml
      behavior: domain

    skk_global:
      type: http
      url: "https://ruleset.skk.moe/Clash/non_ip/global.txt"
      format: txt
      behavior: classical

    my_proxy:
      type: file
      path: local/proxy.yaml
      format: yaml
      behavior: classical
